-- funçãoes de String, data , matemática(number) e conversão de dados 

-----------------FUNÇÕES DE STRING-------------- 
--(LOWER)DEIXA TUDO EM LETRA MAIUSCULA
--(UPPER) DEIXA TUDO EM LETRA MINUSCULA
--(INITCAP)SÓ A INICIAL EM CAP
--(CONCAT) CONCATENA OS CAMPOS
--(LPAD) MUDA AS PALAVRA DE ACORDO COM OS ESPAÇOS
--(RPAD) VAI COLOCAR TUDO NO FINAL QND TIVER ESPAÇOS
--(...)
SELECT NOME, LOWER(NOME)FROM TABELA_DE_CLIENTES; -- EX (LOWER) TUDO MINUSCULO

SELECT NOME, UPPER(NOME)FROM TABELA_DE_CLIENTES; -- EX (UPPER) TUDO MAIUSCULO)

SELECT NOME_DO_PRODUTO, INITCAP(NOME_DO_PRODUTO)FROM TABELA_DE_PRODUTOS; -- EX (INITCAP)DEIXA AS INICIAIS COM LETRA MAIUSCULA

SELECT ENDERECO_1 ,BAIRRO, CONCAT (CONCAT(ENDERECO_1,' ' ),BAIRRO) AS RUA_E_BAIRRO FROM TABELA_DE_CLIENTES; --EX(CONCAT)PEGA OS DOIS TERMOS SELECIONADOS E JUNTA

SELECT NOME_DO_PRODUTO, LPAD(NOME_DO_PRODUTO, 50,'--->') FROM TABELA_DE_PRODUTOS; --EX(LPAD)COLOCA UMA INFO OU ALGO NA FRENTE DO DADO (ATE COMPLETAR OS 70 CARACTERES)

SELECT NOME_DO_PRODUTO, RPAD(NOME_DO_PRODUTO,50,'<---') FROM TABELA_DE_PRODUTOS;  --EX(RPAD) FAZ LITERALMENTE O INVERSO DO LPAD(ESQUERDA PARA DIREITA)

SELECT NOME_DO_PRODUTO, SUBSTR(NOME_DO_PRODUTO,3,5) FROM TABELA_DE_PRODUTOS; --EX(SUBSTR) VAI PEGAR TODA A STRING QUE ESTIVER NA PICIÇÃOS SELECIONADA

SELECT NOME_DO_PRODUTO,INSTR(NOME_DO_PRODUTO,'Campo')FROM TABELA_DE_PRODUTOS; --EX(INSTR) VAI TIRAR APENAS A STRING SELECIONADA

SELECT NOME_DO_PRODUTO, REPLACE(REPLACE (NOME_DO_PRODUTO,'Litro', 'L'),'Ls', 'L')FROM TABELA_DE_PRODUTOS; --EX(REPLACE)ALTERA DADOS (LITROS ----> L)


--------------------FUNÇÃO DE DATAS--------------------
--(TO_CHAR)PEGA O DATA E PASSA PARA TEXTO
--(TO_DATE) TEXTO PARA DATA
--(SYSDATE)HORA E DIA DO COMPUTADOR (MOMENTO EXATO)
--(MONTHS_BETWEEN) DUAS DATAS E ELE APRESENTA O NUMERO DE MESES ENTRE ESSAS DATAS
--(ADD_MONTHS) ADICIONA MESES
--(NEXT_DAY) DEVOLVE O PROXIMO DIA DA SEMANA

SELECT SYSDATE FROM DUAL; --EX(SYSDATE) PEGANDO O MOMENTO EXATO DO PC

SELECT TO_CHAR(SYSDATE, 'DD/MM/YYYY HH:MI:SS')FROM DUAL; --(TO_CHAR + SYSDATE)PASSANDO A DATA EXATA PARA TEXTO

SELECT SYSDATE + 127 FROM DUAL;

SELECT NOME, IDADE, MONTHS_BETWEEN(SYSDATE, DATA_DE_NASCIMENTO)/12 FROM TABELA_DE_CLIENTES; --(MONTHS_BETWEEN)PEGA O TOTAL DE MESES QUE A PESSOA JÁ VIVEU

SELECT ADD_MONTHS(SYSDATE, 10)FROM DUAL; --(ADD_MONTHS)ADD UM QUANTIDADE DE MESES JUNTO COM O SYSDATE

SELECT SYSDATE AS DIA_DE_HJ, NEXT_DAY(SYSDATE,'SEXTA')AS PROXIMA_SEXTA FROM DUAL; --(NEXT_DAY) PUXANDO A PRIMIRA SEXTA DEPOIS DO DIA DE HOJE

SELECT SYSDATE AS DIA_DE_HJ, LAST_DAY(SYSDATE)AS ULTIMO_DIA_MES FROM DUAL; --(LAST_DAY) PUXANDO O ULTIMO DIA DO MES


