-- funçãoes matemática(number) e conversão de dados;

-----------------FUNÇÕES DE NUMBER --------------
--(ROUND)AREDONDA NUMEROS 
--(TRUNC)SEMPRE VAI AREDONDAR PARA BAIXO
--(CEIL) SEMPRE VAI AREDONDAR PARA CIMA 
--(FLOOR)==(TRUNC)
--(POWER)POTENCIA EX (5,10) = 9.000.000++
--(EXP) EXPONENCIAL N = PARAMETRO
--(SQRT) RAIZ QUADRADA
--(SING) NEGATIVO = <1|| NULO = 0 || POSITIVO = 1
--(ABS) VALOR ABSOLUTO
--(MOD) RESTO DA DIVISAO DE DOIS NUMEROS

SELECT 3.4 FROM DUAL;
SELECT ROUND (3.4) FROM DUAL; -- AREDONDA O NUMERO PARA 3

SELECT ROUND (3.6) FROM DUAL; -- AREDONDA O NUMERO PARA 4

SELECT TRUNC (3.6) FROM DUAL; -- MESMO ESTANDO PERTO DO 4 ELE AREDONDA PARA 3

SELECT CEIL (3.2) FROM DUAL; --  MESMO ESTANDO PERTO DO 3 ELE AREDONDA PRARA 4 

SELECT FLOOR  (3.2) FROM DUAL; -- (= TRUNC)

SELECT POWER (2,4) FROM DUAL; -- FEZ A POTENCIA DE 2 ELEVADO A 4

SELECT EXP (4) FROM DUAL; -- PEGA O NUMERO EXPONENCIAL

SELECT SQRT(64)FROM DUAL; -- TIROU A RAIZ QUADRADA DE 64

SELECT MOD(10,6) FROM DUAL; --PEGOU O RESTO DA DIVISAO 

