SELECT DISTINCT NOTAS_FISCAIS.MATRICULA
,TABELA_DE_VENDEDORES.NOME , COUNT (*) AS NUMERO_DE_NOTAS
FROM TABELA_DE_VENDEDORES INNER JOIN NOTAS_FISCAIS
ON NOTAS_FISCAIS.MATRICULA = TABELA_DE_VENDEDORES.MATRICULA  -- INNER JOIN SERVE PARA JUNTAR DUAS TABELAS PARA OBTER DADOS (NÃO ESQUECER DE ADICIONAR O NOME NA FRENTE DOS CAMPOS, E NO FINAL ADICIONAR AS CHAVES COMPOSTAS) 
GROUP BY NOTAS_FISCAIS.MATRICULA, TABELA_DE_VENDEDORES. NOME;


-------------------------------------------------------------------------------
-- OUTROS TIPOS DE JOIN (LEFT JOIN) DA ENFASE PARA A TABELA QUE APARECE NA ESQUEREDA
-- OUTROS TIPOS DE JOIN (RIGTH JOIN) DA ENFASE PARA A TABELA QUE APARECE NA DIREITA
-- OUTROS TIPOS DE JOIN (FULL JOIN) VAI TRAZER TUDO INDEPENDENDE DA CONDIÇÃO
-- OUTROS TIPOS DE JOIN (CROSS JOIN(MUDA A SINTAXE))ANALISE COMBINATORIA
 --------------------------------------------------------------------------------
 
SELECT DISTINCT TC.CPF AS CPF_DO_CADASTRO,
TC.NOME AS NOME_DO_CLIENTE,
NF.CPF AS CPF_NOTA_FISCAL
FROM
TABELA_DE_CLIENTES TC
INNER JOIN
NOTAS_FISCAIS NF
ON
TC.CPF = NF.CPF
ORDER BY NOME_DO_CLIENTE;
--------------------------------------------------------------------------------------
INSERT INTO TABELA_DE_CLIENTES 
(CPF, NOME, ENDERECO_1, ENDERECO_2, BAIRRO, CIDADE, ESTADO, CEP, DATA_DE_NASCIMENTO, IDADE, 
SEXO, LIMITE_DE_CREDITO, VOLUME_DE_COMPRA, PRIMEIRA_COMPRA) 
VALUES ('23412632331', 'Juliana Silva', 'R. Tramandai', '', 'Bangu', 'Rio de Janeiro', 
'RJ', '23400000', TO_DATE('1989-02-04','YYYY-MM-DD'), 28, 'F', 180000.0000, 24500, 0);


SELECT DISTINCT TC.CPF AS CPF_DO_CADASTRO,
TC.NOME AS NOME_DO_CLIENTE,
NF.CPF AS CPF_NOTA_FISCAL
FROM
TABELA_DE_CLIENTES TC
LEFT JOIN
NOTAS_FISCAIS NF
ON
TC.CPF = NF.CPF
ORDER BY NOME_DO_CLIENTE;
---------------------------------------------------
-- OUTRO EXEMPLO UTILIZANDO O JOIN

SELECT
DISTINCT
TV.NOME AS NOME_DO_VENDEDOR,
TV.BAIRRO AS BAIRRO_DO_VENDEDOR,
TC.NOME AS NOME_DO_CLIENTE,
TC.BAIRRO AS BAIRRO_DO_CLIENTE
FROM
TABELA_DE_VENDEDORES TV
INNER JOIN 
TABELA_DE_CLIENTES TC
ON
TV.BAIRRO = TC.BAIRRO;
--(UTILIZANDO O COMANDO LEFT JOIN)
SELECT
DISTINCT
TV.NOME AS NOME_DO_VENDEDOR,
TV.BAIRRO AS BAIRRO_DO_VENDEDOR,
TC.NOME AS NOME_DO_CLIENTE,
TC.BAIRRO AS BAIRRO_DO_CLIENTE
FROM
TABELA_DE_VENDEDORES TV
LEFT JOIN 
TABELA_DE_CLIENTES TC
ON
TV.BAIRRO = TC.BAIRRO;
-- (UTILIZANDO O COMANDO RIGTH JOIN)
SELECT
DISTINCT
TV.NOME AS NOME_DO_VENDEDOR,
TV.BAIRRO AS BAIRRO_DO_VENDEDOR,
TC.NOME AS NOME_DO_CLIENTE,
TC.BAIRRO AS BAIRRO_DO_CLIENTE
FROM
TABELA_DE_VENDEDORES TV
RIGHT JOIN 
TABELA_DE_CLIENTES TC
ON
TV.BAIRRO = TC.BAIRRO;








