SELECT  BAIRRO FROM TABELA_DE_CLIENTES UNION SELECT  BAIRRO FROM TABELA_DE_VENDEDORES;  --(UNION É UMA JUNÇÃO DE DADOS DE DUAS TABELAS QUE POR DEFAUL APLICA O DISTINVT NO FINAL)

SELECT  BAIRRO, 'Cliente' AS ORIGEM FROM TABELA_DE_CLIENTES UNION ALL SELECT  BAIRRO,'vendedor' AS ORIGEMV FROM TABELA_DE_VENDEDORES; --(UNION ALL PEGA TODOS OS TERMOS DOS DADOS SELECIONADOS,MESMO SE REPETINDO)

--------------------------------------------------------------------------------
-- utilizando in 
SELECT DISTINCT BAIRRO FROM TABELA_DE_VENDEDORES;
SELECT * FROM TABELA_DE_CLIENTES WHERE BAIRRO IN ('tijuca' ,'Santo Amaro','Jardins', 'Copacabana');



SELECT * FROM TABELA_DE_CLIENTES WHERE BAIRRO IN
(SELECT DISTINCT BAIRRO FROM TABELA_DE_VENDEDORES);
--------------------------------------------------------------------------------
--having
SELECT EMBALAGEM, SUM(PRECO_DE_LISTA)AS SOMA_PRECO FROM TABELA_DE_PRODUTOS GROUP BY EMBALAGEM HAVING SUM(PRECO_DE_LISTA)>=80;  --(BUSCAR A SOMA DOS PRECOS DAS EMBALAGEMS)


